local c = require("myswamp.colors")

return {
    ["@annotation"]                   = { link = "PreProc" },
    ["@attribute"]                    = { link = "PreProc" },
    ["@boolean"]                      = { link = "Boolean" },
    ["@character"]                    = { link = "Character" },
    ["@character.printf"]             = { link = "SpecialChar" },
    ["@character.special"]            = { link = "SpecialChar" },
    ["@comment"]                      = { link = "Comment" },
    ["@comment.error"]                = { fg = c.error },
    ["@comment.hint"]                 = { fg = c.hint },
    ["@comment.info"]                 = { fg = c.info },
    ["@comment.note"]                 = { fg = c.hint },
    ["@comment.todo"]                 = { fg = c.todo, bold = true },
    ["@comment.warning"]              = { fg = c.warn },
    ["@constant"]                     = { link = "Constant" },
    ["@constant.zig"]                 = { link = "Constant" },
    ["@constant.builtin"]             = { fg = c.builtin },
    ["@constant.macro"]               = { link = "Constant" },
    ["@constructor"]                  = { fg = c.fg },
    ["@diff.delta"]                   = { link = "DiffChange" },
    ["@diff.minus"]                   = { link = "DiffDelete" },
    ["@diff.plus"]                    = { link = "DiffAdd" },
    ["@function"]                     = { link = "Function" },
    ["@function.builtin"]             = { fg = c.builtin }, -- TODO???
    ["@function.call"]                = { link = "@function" },
    ["@function.macro"]               = { link = "Macro" },
    ["@function.method"]              = { link = "Function" },
    ["@function.method.call"]         = { link = "@function.method" },
    ["@keyword"]                      = { link = "Keyword" },
    ["@keyword.conditional"]          = { link = "Conditional" },
    ["@keyword.coroutine"]            = { link = "@keyword" },
    ["@keyword.debug"]                = { link = "Debug" },
    ["@keyword.directive"]            = { link = "PreProc" },
    ["@keyword.directive.define"]     = { link = "Define" },
    ["@keyword.exception"]            = { link = "Exception" },
    ["@keyword.function"]             = { link = "@keyword" },
    ["@keyword.import"]               = { link = "Include" },
    ["@keyword.operator"]             = { link = "@operator" },
    ["@keyword.repeat"]               = { link = "Repeat" },
    ["@keyword.return"]               = { link = "@keyword" },
    ["@keyword.storage"]              = { link = "StorageClass" },
    ["@label"]                        = { fg = c.label },
    -- TODO recolor whole markup section
    ["@markup"]                       = { link = "@none" },
    ["@markup.emphasis"]              = { italic = true },
    ["@markup.environment"]           = { link = "Macro" },
    ["@markup.environment.name"]      = { link = "Type" },
    ["@markup.heading"]               = { link = "Title" },
    ["@markup.italic"]                = { italic = true },
    ["@markup.link"]                  = { fg = c.ohshit },
    ["@markup.link.label"]            = { link = "SpecialChar" },
    ["@markup.link.label.symbol"]     = { link = "Identifier" },
    ["@markup.link.url"]              = { link = "Underlined" },
    ["@markup.list"]                  = { fg = c.ohshit },
    ["@markup.list.checked"]          = { fg = c.ohshit },
    ["@markup.list.markdown"]         = { fg = c.ohshit, bold = true },
    ["@markup.list.unchecked"]        = { fg = c.ohshit },
    ["@markup.math"]                  = { link = "Special" },
    ["@markup.raw"]                   = { link = "String" },
    ["@markup.raw.markdown_inline"]   = { bg = c.bg_dark, fg = c.blue },
    ["@markup.strikethrough"]         = { strikethrough = true },
    ["@markup.strong"]                = { bold = true },
    ["@markup.underline"]             = { underline = true },
    ["@module"]                       = { link = "Include" },
    ["@module.builtin"]               = { fg = c.builtin },
    ["@namespace.builtin"]            = { link = "@variable.builtin" },
    ["@none"]                         = {},
    ["@number"]                       = { link = "Number" },
    ["@number.float"]                 = { link = "Float" },
    ["@operator"]                     = { fg = c.fg_punct },
    ["@property"]                     = { link = "@variable.member" },
    ["@punctuation.bracket"]          = { fg = c.fg_punct },
    ["@punctuation.delimiter"]        = { fg = c.fg_punct },
    ["@punctuation.special"]          = { fg = c.fg_punct },
    ["@punctuation.special.markdown"] = { fg = c.ohshit },
    ["@string"]                       = { link = "String" },
    ["@string.documentation"]         = { fg = c.ohshit },
    ["@string.escape"]                = { fg = c.escape_seq },
    ["@string.regexp"]                = { link = "@string" },
    ["@tag"]                          = { link = "Label" },
    ["@tag.attribute"]                = { link = "@property" },
    ["@tag.delimiter"]                = { link = "Delimiter" },
    ["@type"]                         = { link = "Type" },
    ["@type.builtin"]                 = { link = "@type" },
    ["@type.definition"]              = { link = "Typedef" },
    ["@type.qualifier"]               = { link = "@keyword" },
    ["@variable"]                     = { fg = c.variable },
    ["@variable.builtin"]             = { fg = c.builtin },
    ["@variable.member"]              = { fg = c.member },
    ["@variable.parameter"]           = { fg = c.parameter },
    ["@variable.parameter.builtin"]   = { fg = c.builtin },
}
